# Generated by Django 3.2.9 on 2021-11-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='dificuldade',
            field=models.CharField(choices=[('facil', 'Fácil'), ('mediana', 'Mediana'), ('complexa', 'Complexo')], max_length=8),
        ),
    ]
